# Generated by Django 4.1.2 on 2023-02-24 22:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Info',
            fields=[
                ('admit_date', models.DateField(auto_created=True)),
                ('patient_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_Name', models.CharField(max_length=64)),
                ('last_Name', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('nationality', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('address', models.TextField()),
                ('insurance_policy_ID', models.CharField(max_length=12)),
                ('Nation_Card_ID', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discharge_date', models.DateField(null=True)),
            ],
        ),
    ]
