# Generated by Django 4.1.2 on 2023-02-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='admit_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='nationality',
            field=models.CharField(default='Indian', max_length=20),
        ),
    ]
